gen t=_n
gen newt=tq(1996q1) + t-1
tsset newt
gen newt = tq(1996q1) + t - 1
gen newt1 = tq(1996q1) + t - 1
tsset newt1
tsset newt1, quarterly
drop newt 
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta2}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta5},  beta(0.5,0.2)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta9}, beta(0.5,0.2)) prior({beta10}, beta(0.5,0.2))    rseed(17) :  dsge (  x = F.x - (r - F.p) - {beta1}*de +z +{beta2}*us, unobserved)   (  p = {beta4}*F.p + {beta5}*(F.x - x) +  k  )  (  r = {beta6}*F.r + (1- {beta6})*(p + x + de) + u               )  (de = {beta7}*(r – F.p) + v)  (F.z = {beta3}*z, state                )    (F.k = {beta8}*k, state                )   (F.u = {beta9}*u, state                )  (F.v = {beta10}*v, state                )
gen de=e-l.e
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta2}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta5},  beta(0.5,0.2)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta9}, beta(0.5,0.2)) prior({beta10}, beta(0.5,0.2))    rseed(17) :  dsge (  x = F.x - (r - F.p) - {beta1}*de +z +{beta2}*us, unobserved)   (  p = {beta4}*F.p + {beta5}*(F.x - x) +  k  )  (  r = {beta6}*F.r + (1- {beta6})*(p + x + de) + u               )  (de = {beta7}*(r – F.p) + v)  (F.z = {beta3}*z, state                )    (F.k = {beta8}*k, state                )   (F.u = {beta9}*u, state                )  (F.v = {beta10}*v, state                )
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta2}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta5},  beta(0.5,0.2)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta9}, beta(0.5,0.2)) prior({beta10}, beta(0.5,0.2))    rseed(17) :  dsge (  x = F.x - (r - F.p) - {beta1}*de +z +{beta2}*k, unobserved)   (  p = {beta4}*F.p + {beta5}*(F.x - x) +  k  )  (  r = {beta6}*F.r + (1- {beta6})*(p + x + de) + u               )  (de = {beta7}*(r – F.p) + v)  (F.z = {beta3}*z, state                )    (F.k = {beta8}*k, state                )   (F.u = {beta9}*u, state                )  (F.v = {beta10}*v, state                ) (us=k)
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta2}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta5},  beta(0.5,0.2)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta9}, beta(0.5,0.2)) prior({beta10}, beta(0.5,0.2))    rseed(17) :  dsge (  x = F.x - (r - F.p) - {beta1}*de +z +{beta2}*k, unobserved)   (  p = {beta4}*F.p + {beta5}*(F.x - x) +  k  )  (  r = {beta6}*F.r + (1- {beta6})*(p + x + de) + u               )  (de = {beta7}*(r – F.p) + v)  (F.z = {beta3}*z, state                )    (F.k = {beta8}*k, state                )   (F.u = {beta9}*u, state                )  (F.v = {beta10}*v, state) (us=k)
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta2}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta5},  beta(0.5,0.2)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta9}, beta(0.5,0.2)) prior({beta10}, beta(0.5,0.2))    rseed(17) :  dsge (  x = F.x - (r - F.p) - {beta1}*de +z +{beta2}*k, unobserved)   (  p = {beta4}*F.p + {beta5}*(F.x - x) +  k  )  (  r = {beta6}*F.r + (1- {beta6})*(p + x + de) + u               )  (de = {beta7}*(r - F.p) + v)  (F.z = {beta3}*z, state                )    (F.k = {beta8}*k, state                )   (F.u = {beta9}*u, state                )  (F.v = {beta10}*v, state) (us=k)
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta2}, beta(0.5,0.2)) prior({beta3}, beta(0.5,0.2)) prior({beta4}, beta(0.25,0.05)) prior({beta5},  beta(0.5,0.2)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta9}, beta(0.5,0.2)) prior({beta10}, beta(0.5,0.2))    rseed(17) :  dsge (  x = F.x - (r - F.p) - {beta1}*de +z +{beta2}*k, unobserved)   (  p = {beta4}*F.p + {beta5}*(F.x - x) +  k  )  (  r = {beta6}*F.r + (1- {beta6})*(p + x + de) + u               )  (de = {beta7}*(r - F.p) + v)  (F.z = {beta3}*z, state                )    (F.k = {beta8}*k, state                )   (F.u = {beta9}*u, state                )  (F.v = {beta10}*v, state) (us=k)
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta9}, beta(0.5,0.2)) prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.q + (({beta4}*(2 - {beta4})*(1 - {beta1}))/{beta1})*F.m, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})) + 1)*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})) + 1)*F.q - {beta4}*q + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*l.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*q )   (F.z = {beta3}*z, state                )    (F.q = {beta8}*q, state                )   (F.u = {beta11}*u, state                )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state                )
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.q + (({beta4}*(2 - {beta4})*(1 - {beta1}))/{beta1})*F.m, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})) + 1)*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})) + 1)*F.q - {beta4}*q + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*l.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*q )   (F.z = {beta3}*z, state                )    (F.q = {beta8}*q, state                )   (F.u = {beta11}*u, state                )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state                )
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.q + (({beta4}*(2 - {beta4})*(1 - {beta1}))/{beta1})*F.m, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})) + 1)*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})) + 1)*F.q - {beta4}*q + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*q )   (F.z = {beta3}*z, state                )    (F.q = {beta8}*q, state                )   (F.u = {beta11}*u, state                )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state                )
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.q + (({beta4}*(2 - {beta4})*(1 - {beta1}))/{beta1})*F.m, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})) + 1)*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})) + 1)*F.q - {beta4}*q + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*q )   (F.z = {beta3}*z, state                )    (F.q = {beta8}*q, state                )   (F.u = {beta11}*u, state                )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state                )
clear
gen t=_n
gen newt1 = tq(1996q1) + t - 1
tsset newt1, quarterly
gen de=e-l.e
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.q + (({beta4}*(2 - {beta4})*(1 - {beta1}))/{beta1})*F.m, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})) + 1)*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})) + 1)*F.q - {beta4}*q + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*q )   (F.z = {beta3}*z, state                )    (F.q = {beta8}*q, state                )   (F.u = {beta11}*u, state                )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state                )
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.q + (({beta4}*(2 - {beta4})*(1 - {beta1}))/{beta1})*F.m, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})) + 1)*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})) + 1)*F.q - {beta4}*q + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*q )   (F.z = {beta3}*z, state                )    (F.q = {beta8}*q, state                )   (F.u = {beta11}*u, state                )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.q + (({beta4}*(2 - {beta4})*(1 - {beta1}))/{beta1})*F.m, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})) + 1)*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})) + 1)*F.q - {beta4}*q + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*q )   (F.z = {beta3}*z, state  )    (F.q = {beta8}*q, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.q + {beta4}*(2 - {beta4})*(1 - {beta1})*F.m, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})) + 1)*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})) + 1)*F.q - {beta4}*q + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*q )   (F.z = {beta3}*z, state  )    (F.q = {beta8}*q, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.q + {beta4}*(2 - {beta4})*(1 - {beta1})*F.m, unobserved)  (  p = ({beta6}*F.p + {beta4}*{beta6}*F.q - {beta4}*q + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*q )   (F.z = {beta3}*z, state  )    (F.q = {beta8}*q, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.q + {beta4}*(2 - {beta4})*(1 - {beta1})*F.m, unobserved)  (  p = {beta6}*F.p + {beta4}*{beta6}*F.q - {beta4}*q + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*q )   (F.z = {beta3}*z, state  )    (F.q = {beta8}*q, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) mcmcsize(25000) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.q + {beta4}*(2 - {beta4})*(1 - {beta1})*F.m, unobserved)  (  p = {beta6}*F.p + {beta4}*{beta6}*F.q - {beta4}*q + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*q )   (F.z = {beta3}*z, state  )    (F.q = {beta8}*q, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
dfuller q, lags(0)
dfuller us, lags(0)
dfuller pus, lags(0)
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.q + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m, unobserved)  (  p = ({beta6}*F.p + {beta4}*{beta6}*F.q - {beta4}*q + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*q )   (F.z = {beta3}*z, state  )    (F.q = {beta8}*q, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.q + {beta4}*(2 - {beta4})*(1 - {beta1})*1/{beta1}*F.m, unobserved)  (  p = ({beta6}*F.p + {beta4}*{beta6}*F.q - {beta4}*q + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*q )   (F.z = {beta3}*z, state  )    (F.q = {beta8}*q, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.q + {beta4}*(2 - {beta4})*(1 - {beta1})*F.m, unobserved)  (  p = ({beta6}*F.p + {beta4}*{beta6}*F.q - {beta4}*q + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*q )   (F.z = {beta3}*z, state  )    (F.q = {beta8}*q, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) mcmcsize(25000) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.q + {beta4}*(2 - {beta4})*(1 - {beta1})*F.m, unobserved)  (  p = {beta6}*F.p + {beta4}*{beta6}*F.q - {beta4}*q + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*q )   (F.z = {beta3}*z, state  )    (F.q = {beta8}*q, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) mcmcsize(25000) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.q + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/1/{beta1})*F.m, unobserved)  (  p = {beta6}*F.p + {beta4}*{beta6}*F.q - {beta4}*q + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*q )   (F.z = {beta3}*z, state  )    (F.q = {beta8}*q, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) mcmcsize(25000) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.q + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*{beta6}*F.q - {beta4}*q + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*q )   (F.z = {beta3}*z, state  )    (F.q = {beta8}*q, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) mcmcsize(25000) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.q + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.q - {beta4}*q + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*q )   (F.z = {beta3}*z, state  )    (F.q = {beta8}*q, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) mcmcsize(5000) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.q + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.q - {beta4}*q + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*q )   (F.z = {beta3}*z, state  )    (F.q = {beta8}*q, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) mcmcsize(30000) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.q + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.q - {beta4}*q + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*q )   (F.z = {beta3}*z, state  )    (F.q = {beta8}*q, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
bayesgraph diagnostics {beta1}
gen dq=ln(q/l.q)
dfuller dq, lags(0)
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) mcmcsize(30000) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.dq + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.dq - {beta4}*dq + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*dq )   (F.z = {beta3}*z, state  )    (F.dq = {beta8}*dq, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
bayesgraph diagnostics {beta1}
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) mcmcsize(1000) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.dq + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.dq - {beta4}*dq + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*dq )   (F.z = {beta3}*z, state  )    (F.dq = {beta8}*dq, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
bayesgraph diagnostics {beta1}
bayesgraph diagnostics {beta1}
bayesgraph diagnostics {beta2}
bayesgraph diagnostics {beta3}
bayesgraph diagnostics {beta12}
bayes, saving(nk_mcmc.dta, replace)
bayesirf set bayes_irfs.irf, replace
bayesirf create nk_model
bayesirf graph irf, impulse(r) response(x p r q)
bayesirf graph irf, impulse(r) response(x p r de dq)
bayesirf graph irf, impulse(u) response(x p r de dq)
bayesgraph diagnostics {beta1}
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(17) mcmcsize(12500) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.dq + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.dq - {beta4}*dq + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*dq )   (F.z = {beta3}*z, state  )    (F.dq = {beta8}*dq, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
bayesgraph diagnostics {beta1}
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(123) mcmcsize(1500) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.dq + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.dq - {beta4}*dq + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*dq )   (F.z = {beta3}*z, state  )    (F.dq = {beta8}*dq, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
bayesgraph diagnostics {beta1}
bayesgraph diagnostics {beta2}
bayesgraph diagnostics {beta3}
bayesgraph trace {beta1}
bayes, saving(nk_mcmc1.dta, replace)
bayesirf set bayes_irfs.irf, replace
bayesirf create nk_model
bayesirf graph irf, impulse(u) response(x p r de dq)
bayesirf table irf, impulse(r) response(x)
bayesirf table irf, impulse(u) response(x)
bayesgraph trace _all, byparm
bayesgraph trace _all, byparm[beta1 beta2 beta3]
bayesgraph trace _all, byparm[(beta1 beta2 beta3)]
bayesgraph trace _all, byparm(beta1 beta2 beta3)
bayesgraph trace _all, byparm({beta1} {beta2} {beta3})
bayesgraph trace {beta1}, name(beta1) lcolor(red)
bayesgraph trace {beta3}, name(beta3) lcolor(red)
graph combine beta1 beta3
bayesgraph trace {beta1}, name(beta1) lcolor(red) skip(500)
bayesgraph trace {beta1}, name(beta1) lcolor(red) ci
bayesgraph trace {beta1}, name(beta1) lcolor(red) graph#opts(ci)
bayesgraph trace {beta1}, name(beta1) lcolor(red) graphopts(ci)
bayesgraph trace {beta1}, graphopts(ci)
bayesgraph trace {beta1}, ci
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(123) mcmcsize(1500) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.dq + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.dq - {beta4}*dq + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*dq )   (F.z = {beta3}*z, state  )    (F.dq = {beta8}*dq, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
putexcel A1=(" ") B1=("Mean") C1=("Std. dev.") D1=("MCSE") D2=("Median")  using results, replace
cd "F:\ổ đĩa D 31.03.2020\papers\SCOPUS\dsge"
putexcel A1=(" ") B1=("Mean") C1=("Std. dev.") D1=("MCSE") D2=("Median")  using re, replace
putexcel A1=(" ") B1=("Mean") C1=("Std. dev.") D1=("MCSE") D2=("Median")
putexcel A1=(" ") B1=("Mean") C1=("Std. dev.") D1=("MCSE") D2=("Median") using
putexcel set re
putexcel set re1
putexcel A1=(" ") B1=("Mean") C1=("Std. dev.") D1=("MCSE") D2=("Median")
putexcel set re1
putexcel set re2
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(123) mcmcsize(1500) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.dq + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.dq - {beta4}*dq + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*dq )   (F.z = {beta3}*z, state  )    (F.dq = {beta8}*dq, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
putexcel A1=(" ") B1=("Mean") C1=("Std. dev.") D1=("MCSE") D2=("Median")
ereturn
ereturn list
putexcel A1=("e(scparams) ") B1=("e(mean)") C1=("e(sd)") D1=("e(mcse)") D2=("e(median)")
putexcel A1=("e(scparams) ") B1=("e(mean)") C1=("e(sd)") D1=("e(mcse)") E1=("e(median)"),replace
putexcel set re3
putexcel A1=("e(scparams) ") B1=("e(mean)") C1=("e(sd)") D1=("e(mcse)") E1=("e(median)")
putexcel A1=(e(scparams)) B1=(e(mean)) C1=(e(sd)) D1=(e(mcse)) E1=(e(median))
putexcel A1=e(scparams)
putexcel A1='e(scparams)'
putexcel A1=`e(scparams)'
putexcel A1=`e(mean)'
putexcel A1=(`e(mean)')
putexcel set re4
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) rseed(123) mcmcsize(1500) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.dq + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.dq - {beta4}*dq + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*dq )   (F.z = {beta3}*z, state  )    (F.dq = {beta8}*dq, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   )
putexcel A1=(`e(mean)')
putexcel A1=(e(mean))
putexcel A1=('e(mean)')
putexcel A1='e(mean)'
putexcel A1=e(mean)
set scheme economist 
bayesgraph trace {beta1}
set scheme s1rcolor
bayesgraph trace {beta1}
set scheme uncluttered
help scheme files
set scheme s2mono
bayesgraph trace {beta1}
bayesgraph trace {beta1}, lcolor(red)
set scheme s2gcolor
bayesgraph trace {beta1}, lcolor(red)
s2mono
set scheme s2manual
bayesgraph trace {beta1}, lcolor(red)
set scheme s2color
bayesgraph trace {beta1}, lcolor(red)
bayesgraph trace {beta1}, lcolor(red)
set scheme   s2manual
bayesgraph trace {beta1}, lcolor(red)
bayesgraph trace {beta1}, lcolor(red) acopts(ci)
set scheme s1mono
bayesgraph trace {beta1}, lcolor(red)
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) prior({sd(e.covid)},normal(0.0822,0.0016)) prior({beta13}, beta(0.7,0.1)) rseed(123) mcmcsize(1500) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.dq + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m -{beta13}*covid, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.dq - {beta4}*dq + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*dq )   (F.z = {beta3}*z, state  )    (F.dq = {beta8}*dq, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   ) (F.covid={beta13}*covid,state)
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) prior({sd(e.covid)},normal(0.0822,0.0016)) prior({beta13}, beta(0.7,0.1)) rseed(123) mcmcsize(1500) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.dq + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m -{beta13}*covid, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.dq - {beta4}*dq + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*dq )   (F.z = {beta3}*z, state  )    (F.dq = {beta8}*dq, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   ) (F.covid=covid,state)
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) prior({beta14},normal(0.0822,0.0016)) prior({beta13}, beta(0.7,0.1)) rseed(123) mcmcsize(1500) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.dq + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m -{beta13}*covid, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.dq - {beta4}*dq + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*F.r + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*dq )   (F.z = {beta3}*z, state  )    (F.dq = {beta8}*dq, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   ) (F.covid={beta14}*covid,state)
bayes, saving(nk_mcmc2.dta, replace)
bayesirf set bayes_irfs.irf, replace
bayesirf create nk_model2
bayesirf graph irf, impulse(covid) response(x p r de dq)
set scheme plotplainblind
findit plotplainblind
set scheme plotplainblind
bayesgraph trace {beta1}, lcolor(red)
bayesgraph trace {beta1}
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) prior({beta14},normal(0.0822,0.0016)) prior({beta13}, beta(0.7,0.1)) rseed(123) mcmcsize(1500) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.dq + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m -{beta13}*covid, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.dq - {beta4}*dq + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*(F.x - x)     )    (  r = {beta7}*Lr + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*dq )   (F.z = {beta3}*z, state  )    (F.dq = {beta8}*dq, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   ) (F.covid={beta14}*covid,state) (F.Lr = r, state noshock)
bayes, saving(nk_mcmc3.dta, replace)
bayesirf set bayes_irfs1.irf, replace
bayesirf create nk_model3
bayesirf graph irf, impulse(covid) response(x p r de dq)
bayesirf graph irf, impulse(u) response(x p r de dq)
bayesirf graph irf, impulse(u) response(x p r)
bayesirf graph irf, impulse(covid) response(x p r)
bayesirf graph irf, impulse(covid) response(x p r)
bayesirf graph irf, impulse(z) response(x p r)
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) prior({beta14},normal(0.0822,0.0016)) prior({beta13}, beta(0.7,0.1)) rseed(123) mcmcsize(1500) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.dq + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m -{beta13}*covid, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.dq - {beta4}*dq + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*x)     )    (  r = {beta7}*Lr + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*dq )   (F.z = {beta3}*z, state  )    (F.dq = {beta8}*dq, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   ) (F.covid={beta14}*covid,state) (F.Lr = r, state noshock)
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) prior({beta14},normal(0.0822,0.0016)) prior({beta13}, beta(0.7,0.1)) rseed(123) mcmcsize(1500) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.dq + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m -{beta13}*covid, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.dq - {beta4}*dq + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*x     )    (  r = {beta7}*Lr + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*dq )   (F.z = {beta3}*z, state  )    (F.dq = {beta8}*dq, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   ) (F.covid={beta14}*covid,state) (F.Lr = r, state noshock)
bayes, saving(nk_mcmc4.dta, replace)
bayesirf set bayes_irfs2.irf, replace
bayesirf create nk_model4
bayesirf graph irf, impulse(covid) response(x p r)
bayesirf graph irf, impulse(z) response(x p r)
bayesirf graph irf, impulse(u) response(x p r)
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) prior({beta14},normal(0.0822,0.0016)) prior({beta13}, beta(0.7,0.1)) rseed(145) mcmcsize(2500) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.dq + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m -{beta13}*covid, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.dq - {beta4}*dq + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*x     )    (  r = {beta7}*Lr + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*dq )   (F.z = {beta3}*z, state  )    (F.dq = {beta8}*dq, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   ) (F.covid={beta14}*covid,state) (F.Lr = r, state noshock)
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) prior({beta14},normal(0.0822,0.0016)) prior({beta13}, beta(0.7,0.1)) rseed(145) mcmcsize(12500) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) - {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.dq + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m -{beta13}*covid, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.dq - {beta4}*dq + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*x     )    (  r = {beta7}*Lr + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*dq )   (F.z = {beta3}*z, state  )    (F.dq = {beta8}*dq, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   ) (F.covid={beta14}*covid,state) (F.Lr = r, state noshock)
bayesgraph trace {beta1}, lcolor(red)
bayesgraph trace {beta3}, lcolor(red)
bayesgraph trace {beta4}, lcolor(red)
bayesgraph trace {beta7}, lcolor(red)
bayes, saving(nk_mcmc5.dta, replace)
bayesirf set bayes_irfs3.irf, replace
bayesirf create nk_model5
bayesirf graph irf, impulse(covid) response(x p r)
bayesirf graph irf, impulse(z) response(x p r)
bayesirf graph irf, impulse(u) response(x p r)
bayesirf graph irf, impulse(q) response(x p r)
bayesirf graph irf, impulse(dq) response(x p r)
bayesirf graph irf, impulse(de) response(x p r)
bayesgraph kdensity {beta1}, lcolor(red) addplot(function Prior=betaden(0.5,0.2,x), legend(on label(1 "Posterior")) lcolor(blue)) name(beta1)
bayesirf graph irf, impulse(q) response(x p r)
bayesirf graph irf, impulse(covid) response(x p r)
grstyle init
grstyle set plain, grid
grstyle set ci
bayesirf graph irf, impulse(covid) response(x p r)
set scheme plotplainblind
bayesirf graph irf, impulse(covid) response(x p r)
grstyle set color p#lineplot
grstyle set color economist, p#lineplot
ssc install palettes
grstyle set color economist, p#lineplot
ssc install colrspace
grstyle set color economist, p#lineplot
grstyle set color economist, xyline
grstyle set color economist: p#lineplot
bayesirf graph irf, impulse(covid) response(x p r)
set scheme sj
bayesirf graph irf, impulse(covid) response(x p r)
set scheme economist
bayesirf graph irf, impulse(covid) response(x p r)
set scheme s2color
bayesirf graph irf, impulse(covid) response(x p r)
grstyle set plain, horizontal grid
bayesirf graph irf, impulse(covid) response(x p r)
grstyle init
grstyle set plain, horizontal grid
bayesirf graph irf, impulse(covid) response(x p r)
bayesirf graph irf, impulse(covid) response(x p r dq)
bayesirf graph irf, impulse(covid) response(x p r de)
bayesirf graph irf, impulse(u) response(x p r de)
bayesirf graph irf, impulse(z) response(x p r de)
bayesirf graph irf, impulse(us) response(x p r de)
bayesirf graph irf, impulse(m) response(x p r de)
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) prior({beta14},normal(0.0822,0.0016)) prior({beta13}, beta(0.7,0.1)) rseed(145) mcmcsize(12500) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) + {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.dq + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m -{beta13}*covid, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.dq - {beta4}*dq + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*x     )    (  r = {beta7}*Lr + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*dq )   (F.z = {beta3}*z, state  )    (F.dq = {beta8}*dq, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   ) (F.covid={beta14}*covid,state) (F.Lr = r, state noshock)
bayes, saving(nk_mcmc6.dta, replace)
bayesirf set bayes_irfs4.irf, replace
bayesirf create nk_model6
bayesirf graph irf, impulse(covid) response(x p r dq)
bayesirf graph irf, impulse(covid) response(x p r de)
bayesirf graph irf, impulse(u) response(x p r de)
bayesirf graph irf, impulse(z) response(x p r de)
bayesirf table irf, impulse(covid) response(x)
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) prior({sd(e.covid)},normal(0.322,0.01)) prior({beta14}, uniform(1,1)) prior({beta13}, beta(0.7,0.1)) rseed(145) mcmcsize(12500) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) + {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.dq + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m -{beta13}*covid, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.dq - {beta4}*dq + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*x     )    (  r = {beta7}*Lr + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*dq )   (F.z = {beta3}*z, state  )    (F.dq = {beta8}*dq, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   ) (F.covid={beta14}*covid,state) (F.Lr = r, state noshock)
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) prior({sd(e.covid)},normal(0.322,0.01)) prior({beta14}, uniform(0,1)) prior({beta13}, beta(0.7,0.1)) rseed(145) mcmcsize(12500) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) + {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.dq + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m -{beta13}*covid, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.dq - {beta4}*dq + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*x     )    (  r = {beta7}*Lr + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*dq )   (F.z = {beta3}*z, state  )    (F.dq = {beta8}*dq, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   ) (F.covid={beta14}*covid,state) (F.Lr = r, state noshock)
bayes, saving(nk_mcmc7.dta, replace)
bayesirf set bayes_irfs5.irf, replace
bayesirf create nk_model7
bayesirf graph irf, impulse(covid) response(x p r dq)
bayesirf graph irf, impulse(covid) response(x p r de)
bayesirf table irf, impulse(covid) response(x)
bayes, prior({beta1},  beta(0.5,0.2))  prior({beta3}, beta(0.5,0.2))  prior({beta4}, beta(0.25,0.05)) prior({beta6}, gamma(0.5,0.25)) prior({beta7}, beta(0.5,0.2))  prior({beta8}, beta(0.5,0.2))  prior({beta10}, beta(0.5,0.2))  prior({beta11}, normal(2,2))  prior({beta12}, beta(0.5,0.2)) prior({beta14},normal(0.0822,0.0016)) prior({beta13}, beta(0.7,0.1)) rseed(145) mcmcsize(12500) :  dsge  (  x = F.x - ({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*(r - F.p) + {beta3}*z - {beta4}*({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1}))*F.dq + {beta4}*(2 - {beta4})*(1 - {beta1})*(1/{beta1})*F.m -{beta13}*covid, unobserved)  (  p = ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.p + {beta4}*({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*F.dq - {beta4}*dq + ({beta6}/({beta1} + {beta4}*(2 - {beta4})*(1 - {beta1})))*x     )    (  r = {beta7}*Lr + (1- {beta7})*(p + x + de) + u               )   (de = p - pus - (1 - {beta4})*dq )   (F.z = {beta3}*z, state  )    (F.dq = {beta8}*dq, state )   (F.u = {beta11}*u, state )  (F.pus = {beta10}* pus, state                ) (us = m)    (F.m = {beta12}*m, state   ) (F.covid={beta14}*covid,state) (F.Lr = r, state noshock)
bayes, saving(nk_mcmc8.dta, replace)
bayesirf set bayes_irfs6.irf, replace
bayesirf create nk_model8
bayesirf table irf, impulse(covid) response(x)
bayesirf table irf, impulse(covid) response(R)
bayesirf table irf, impulse(covid) response(r)
bayesirf table irf, impulse(u) response(r)
bayesirf table irf, impulse(u) response(x)
bayesirf table irf, impulse(z) response(x)
bayesirf table irf, impulse(z) response(r)
bayesgraph diagnostics {beta1}
export delimited using "C:\Users\DELL\Desktop\demo\datasbv.csv", replace
save "F:\ổ đĩa D 31.03.2020\papers\SCOPUS\dsge\data.dta"
